title: Get a check from Donald Knuth 
why: Prove that you have every bug in the world
how: Fix a bug in tex
validation: Post a photo of your check
links: 
  - Knuth reward: https://en.wikipedia.org/wiki/Knuth_reward_check
