---
paths:
  # Where to get skills, teams etc from
  data: config
server:
  httpPort: 3000
database:
  host: 127.0.0.1:27017
  collection: security-belt
  # leave empty when no authentication is required, e.g when developing locally
  user:
  password:
