title: Personal password manager
why: Only strong passwords are good passwords. You should not be able to memorize them
how: Everyone in the team uses a password manager
validation: Ask all your team members 
links:
  - Pass (CLI): https://www.passwordstore.org/
  - KeePass: http://keepass.info/
  - 1Password: https://1password.com/
  - Enpass: https://www.enpass.io/
